name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # 这个是 OIDC 必备的免密通行证权限
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: 'https://registry.npmjs.org/'
          
      - name: Install dependencies & Generate Image Meta
        run: |
          npm install
          npm run build
          
      - name: Publish to NPM via OIDC (Provenance)
        run: npm publish --provenance --access public
